name: Python Crawler Bot

on:
  schedule:
    # 每周日 12 点运行
    - cron: '0 4 * * 0'

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  bot:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: Running
        run: python3 ./crawlers/bv_crawler.py
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
